#!/bin/bash

chmod o+r stensils/*

LAMBDAS=('-0.005' '-0.003' '-0.002' '-0.001' '0.00' '0.001' '0.003' '0.005')
declare -A RANGES=(['1']='0.6' ['2']='0.52' ['4']='0.505' ['8']='0.505' ['15']='0.505' ['30']='0.505'['60']='0.505' ['130']='0.505')
for radius in "${!RANGES[@]}"
do
	number="${RANGES[$radius]}"
	for displacement in "${LAMBDAS[@]}"
	do
		lambda=$(echo $number + $displacement | bc)
		./CPLinux $radius 35000 3 $lambda p &
	done
	wait
	echo $radius
done
