#!/bin/bash

chmod o+r stensils/*

LAMBDAS=('-0.02' '-0.015' '-0.01' '-0.005' '0.00' '0.005' '0.01' '0.015')
declare -A RANGES=(['1']='0.59' ['2']='0.55' ['4']='0.52' ['8']='0.51' ['15']='0.51' ['30']='0.51')
for radius in "${!RANGES[@]}"
do
	number="${RANGES[$radius]}"
	for displacement in "${LAMBDAS[@]}"
	do
		lambda=$(echo $number + $displacement | bc)
		./CPLinux $radius 10000 5 $lambda p &
	done
	wait
	echo $radius
done
