#!/bin/bash

chmod o+r stensils/*

LAMBDAS=('1.25' '1.0' '0.9' '0.8' '0.75' '0.7' '0.6' '0.5')
FILES=stensils/*
for file in $FILES
do
	current_file=$(echo $(basename $file))   
	number=$(echo $current_file | tr -dc '0-9')  
	for lambda in "${LAMBDAS[@]}"
	do
		current_file=$(echo $(basename $file))
		number=$(echo $current_file | tr -dc '0-9')
		./CPLinux $number 100000 1 $lambda p &
	done
	wait
	echo $number
done
